Django/django/02. django_templates/practice/articles/urls.py
from django.urls import path
from . import views

app_name='articles'
urlpatterns = [
    path('', views.index),
    path('index/', views.index),
    path('dinner/', views.dinner),
    path('search/', views.search),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch),
    path('articles/<int:num>/', views.detail),
]

Django/django/02. django_templates/practice/articles/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    name = 'jayden'
    context = {
        'name': name,
        'name_length': len(name)
    }
    return render(request, 'articles/index.html', context)

import random
def dinner(request):
    foods = ['국밥', '국수', '카레', '탕수육', '스팸']
    pick_me = random.choice(foods)
    context = {
        'foods': foods,
        'pick_me': pick_me
    }
    return render(request, 'articles/dinner.html', context)

def search(request):
    context = {}
    return render(request, 'articles/search.html', context)

def throw(request):
    return render(request, 'articles/throw.html')

# 아래 로직에서 클라이언트로부터 받은 데이터를 활용할 수 있다. 

def catch(request):
    context = {
        'message': request.GET.get('message')
    }
    return render(request, 'articles/catch.html', context)

def detail(request, num):
    context = {
        'num': num
    }
    return render(request, 'articles/detail.html', context)

Django/django/02. django_templates/practice/articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>여기는 부모 템플릿입니다... 그리고 윗부분</h1>
  {% block content %}
  {% endblock content %}

  <h2>여기도 부모 템플릿.. 그리고 여기는 아래지롱~~</h2>
  {% block content2 %}
  {% endblock content2 %}

  <h1>마지막 부분이지롱~~</h1>
</body>
</html>

Django/django/02. django_templates/practice/articles/templates/articles/catch.html
{% extends "articles/base.html" %}

{% block content %}
<h1>잡았다 이놈 {{ message }}</h1>
{% endblock content %}

Django/django/02. django_templates/practice/articles/templates/articles/detail.html
{% extends "articles/base.html" %}

{% block content %}
<h1> {{ num }} 번 게시글!!</h1>
{% endblock content %}

Django/django/02. django_templates/practice/articles/templates/articles/dinner.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>{{ foods }}</h1>
  <h2>랜덤하게 선정된 메뉴는 {{ pick_me }} 이고, {{ pick_me|length }}</h2>
  <ul>메뉴판</ul>
  {% for food in foods %}
    <li>{{ food }}</li>
  {% endfor %}

  {% if foods|length == 0 %}
  <h1>음식이 없습니다.</h1>
  {% else %}
  <h2>음식이 있습니다. </h2>
  {% endif %}
</body>
</html>

Django/django/02. django_templates/practice/articles/templates/articles/index.html
{% extends "articles/base.html" %}

{% block content %}
<h3>윗 부분의 이름은 {{ name }}</h3>
{% endblock content %}

{% block content2 %}
<h3>아래 부분의 내 이름의 길이 {{ name|length }}</h3>
{% endblock content2 %}

Django/django/02. django_templates/practice/articles/templates/articles/search.html
{% extends "articles/base.html" %}

{% block content %}
<form action="https://search.naver.com/search.naver" method="GET">
  <label for="message">검색어</label>
  <input type="text" name="query" id="message">
  <input type="submit" value="제출하기">
</form>
{% endblock content %}

Django/django/02. django_templates/practice/articles/templates/articles/throw.html
{% extends "articles/base.html" %}

{% block content %}
<h1>Throw 페이지</h1>

<form action="{% url "articles:throw" %}" method="GET">
  <input type="text" name="message" id="message">
  <input type="submit">
</form>
{% endblock content %}