Django/django/05. django_orm_with_view/05_study_codes/articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    # path('delete/<int:pk>/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
]

Django/django/05. django_orm_with_view/05_study_codes/articles/models.py
from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Django/django/05. django_orm_with_view/05_study_codes/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    # 전체 게시글 조회 
    # DJango ORM => QuerySetAPI 
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

# 단일 게시글 조회 
# pk: 조회하고 싶은 게시글의 고유 ID 
def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)


# 게시글 작성 페이지를 반환하는 함수 
def new(request):
    return render(request, 'articles/new.html')


# 사용자가 입력한 데이터를 입력받고, 해당 데이터를 저장하는 함수 
def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')

    article = Article.objects.create(title=title, content=content)

    # return render(request, 'articles/create.html')
    return redirect('articles:detail', article.pk)


# 입력받은 pk 게시글을 삭제하는 로직 
def delete(request, pk):
    # 삭제부터 하자. 
    # 어떤 객체를 삭제할 지 먼저 조회를 해야한다.
    article = Article.objects.get(pk=pk).delete()

    # 삭제한 다음에 일반적으로 '삭제를 완료했습니다'
    return redirect('articles:index')

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article
    }
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    update_title = request.POST.get('title')
    update_content = request.POST.get('content')
    print(update_title)
    print(update_content)
    article = Article.objects.get(pk=pk)
    article.title = update_title
    article.content = update_content
    article.save()
    # 업데이트 후에는 게시글 상세페이지로 돌려보내서
    # 제대로 업데이트됐는지 확일할 수 있게 하는게 조금더 정상같죠?
    return redirect('articles:detail', article.pk)

    

Django/django/05. django_orm_with_view/05_study_codes/articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block content %}
  {% endblock content %}
</body>
</html>

Django/django/05. django_orm_with_view/05_study_codes/articles/templates/articles/create.html
{% extends "articles/base.html" %}

{% block content %}
<h1>게시글 생성이 완료됐습니다!!!</h1>
{% endblock content %}

Django/django/05. django_orm_with_view/05_study_codes/articles/templates/articles/detail.html
{% extends "articles/base.html" %}

{% block content %}
<h1>DETAIL</h1>
<h2>{{ article.pk}} 번째 글</h2>
<hr>
<p>제목: {{ article.title}}</p>
<p>내용: {{ article.content}}</p>
<p>작성 시각: {{ article.created_at}}</p>
<p>최신 수정 시각: {{ article.updated_at}}</p>
<hr>
<a href="{% url "articles:edit" article.pk %}">[게시글 수정하기]</a>
<form action="{% url "articles:delete" article.pk %}" method="POST">
  {% csrf_token %}
  <input type="submit" value="게시글 삭제하기">
</form>

<a href="{% url "articles:index" %}">[back]</a>
{% endblock content %}

Django/django/05. django_orm_with_view/05_study_codes/articles/templates/articles/edit.html
{% extends "articles/base.html" %}

{% block content %}
<h1>Edit(수정 페이지)</h1>

<form action="{% url "articles:update" article.pk %}" method="POST">
  {% csrf_token %}
  <div>
    <label for="title">title: </label>
    <input type="text" name="title" id="title" value="{{ article.title}}">
  </div>
  
  <div>
    <label for="content">Content: </label>
    <input type="content" name="content" id="content" value='{{ article.content}}'>
  </div>
  
  <input type="submit" value="게시글 수정하기">
</form>
{% endblock content %}

Django/django/05. django_orm_with_view/05_study_codes/articles/templates/articles/index.html
{% extends "articles/base.html" %}

{% block content %}
<h1>게시글 전체 목록</h1>
<hr>
<a href="{% url "articles:new" %}">게시글 작성하기</a>
<hr>
{% for article in articles %}
  <p>게시글 번호: {{ article.pk }}</p>
  <a href="{% url "articles:detail" article.pk %}">
    <p>게시글 제목: {{ article.title}}</p>
  </a>
  <p>게시글 내용: {{ article.content }}</p>
  <hr>
{% endfor %}
{% endblock content %}

Django/django/05. django_orm_with_view/05_study_codes/articles/templates/articles/new.html
{% extends "articles/base.html" %}

{% block content %}
<h1>게시글 작성 페이지(NEW)</h1>

<form action="{% url "articles:create" %}" method="POST">
  {% csrf_token %}
  <div>
    <label for="title">title: </label>
    <input type="text" name="title" id="title">
  </div>
  
  <div>
    <label for="content">Content: </label>
    <input type="content" name="content" id="content">
  </div>
  
  <input type="submit" value="게시글 저장하기">
</form>
<hr>
<a href="{% url "articles:index" %}">게시글 목록으로 돌아가기</a>
{% endblock content %}