Django/django/04. django_orm/skeleton_codes/articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="articles"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('search/', views.search, name="search"),
    path('search_result/', views.search_result, name="search_result"),
    path('detail/<int:num>', views.detail, name="detail"),
]

Django/django/04. django_orm/skeleton_codes/firstproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

Django/django/04. django_orm/skeleton_codes/pages/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
]

Django/django/04. django_orm/skeleton_codes/articles/models.py
from django.db import models

Django/django/04. django_orm/skeleton_codes/pages/models.py
from django.db import models

# Create your models here.

Django/django/04. django_orm/skeleton_codes/articles/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'articles/index.html')

def search(request):
    return render(request, 'articles/search.html')

def search_result(request):
    request_data = request.GET
    print(request_data)
    context = {
        'num': request_data.get('num')
    }
    return render(request, 'articles/search_result.html', context)


def detail(request, num):
    context = {
        'num': num
    }
    return render(request, 'articles/detail.html', context)

Django/django/04. django_orm/skeleton_codes/pages/views.py
from django.shortcuts import render

# Create your views here.

Django/django/04. django_orm/skeleton_codes/articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>베이스 템플릿이 기본으로 실행된다.</h1>
  {% block content %}

  {% endblock content %}

  <h1>content block 밑에 입니다.</h1>
</body>
</html>

Django/django/04. django_orm/skeleton_codes/articles/templates/articles/detail.html
{% extends "articles/base.html" %}

{% block content %}
<h1>{{ num }} 상세 페이지입니다!!!</h1>
{% endblock content %}

Django/django/04. django_orm/skeleton_codes/articles/templates/articles/index.html
{% extends "articles/base.html" %}

{% block content %}
<h1>인덱스 페이지입니다.!</h1>
{% endblock content %}

Django/django/04. django_orm/skeleton_codes/articles/templates/articles/search.html
{% extends "articles/base.html" %}

{% block content %}
<form action="{% url "articles:search_result" %}" method="GET">
  <input type="number" name="num" id="num">
  <input type="submit" value="찾아보기">
</form>
{% endblock content %}

Django/django/04. django_orm/skeleton_codes/articles/templates/articles/search_result.html
{% extends "articles/base.html" %}

{% block content %}
<a href="{% url "articles:detail" num %}">여기를 누르면 {{ num }}디테일 페이지로 갑니다.</a>
{% endblock content %}